package com.commander.config;

import java.io.File;

public class FileConfig {
    public static final boolean USE_INNER_FILE = true;
    public static final String FILE_DIR_PATH = "file";
    public static final String IMAGE_DIR_PATH = "image";
    public static final String FONT_DIR_PATH = "font";
    public static final String STAGE_DIR_PATH = "stage";
    public static final String MAP_FILE_PREFIX = "map_";
    public static final String CHARACTERS_FILE_PREFIX = "characters_";
    public static final String FILE_FORMAT = ".csv";
    public static final String IMAGE_FORMAT = ".gif";
    public static final String IMAGE_FORMAT_PNG = ".png";
    public static final String TEXT_FORMAT = ".txt";
    public static final String CHARACTER_FILE_PATH = FILE_DIR_PATH + File.separator + "characters" + FILE_FORMAT;
    public static final String ATTACK_SKILL_FILE_PATH = FILE_DIR_PATH + File.separator + "attackskills" + FILE_FORMAT;
    public static final String DEFENSE_SKILL_FILE_PATH = FILE_DIR_PATH + File.separator + "defenseskills" + FILE_FORMAT;
    public static final String RECOVER_SKILL_FILE_PATH = FILE_DIR_PATH + File.separator + "recoverskills" + FILE_FORMAT;
    public static final String CHARACTER_SKILL_FILE_PATH = FILE_DIR_PATH + File.separator + "charactersskills" + FILE_FORMAT;
    public static final String MAPCHIP_FILE_PATH = FILE_DIR_PATH + File.separator + "mapchips" + FILE_FORMAT;
    public static final String BRAIN_FILE_PATH = FILE_DIR_PATH + File.separator + "brains" + FILE_FORMAT;
    public static final String CHARA_EXPRESSION_KEY_NORMAL = "normal";
    public static final String CHARA_EXPRESSION_KEY_WAIT = "wait";
    public static final String CHARA_EXPRESSION_KEY_ATTACK = "attack";
    public static final String CHARA_EXPRESSION_KEY_WIN = "win";
    public static final String CHARA_EXPRESSION_KEY_PINCH = "pinch";
    public static final String CHARA_EXPRESSION_KEY_LOSE = "lose";
    public static final String BALL1_KEY = "ball1";
    public static final String BALL2_KEY = "ball2";
    public static final String OBSTACLE_KEY = "obstacle";
    public static final String SIDE_WALL_KEY = "sidewall";
    public static final String BOTTOM_WALL_KEY = "bottomwall";
    public static final String RIGHT_ARROW_KEY = "right_arrow";
    public static final String LEFT_ARROW_KEY = "left_arrow";
    public static final String BUTTOM_KEY = "buttom";
    public static final String STAR_KEY = "star";
    public static final String SMALL_DAMAGE_KEY = "damage1";
    public static final String BIG_DAMAGE_KEY = "damage2";
    public static final String RED_STAR_KEY = "red_star";
    public static final String BLUE_STAR_KEY = "blue_star";
    public static final String RED_RECOVER_KEY = "red_recover";
    public static final String BLUE_RECOVER_KEY = "blue_recover";
    public static final String EXPLODE_KEY = "explode";
    public static final String ATTACK_KEY = "attack";
    public static final String WIN_KEY = "win";
    public static final String LOSE_KEY = "lose";
    public static final String WAVING_KEY_0 = "waving0";
    public static final String WAVING_KEY_1 = "waving1";
    public static final String WAVING_KEY_2 = "waving2";
    public static final String WAVING_KEY_3 = "waving3";
    public static final String WAVING_KEY_4 = "waving4";
    public static final String TITLE_IMAGE_KEY = "title_image";
    public static final String SLEEPING_IMAGE_KEY = "sleeping";
    public static final String GOTHIC_FONT_KEY = "gothic";
    public static final String NYANKO_FONT_KEY = "haranyan";
    public static final int IMAGE_SPLITTED_WIDTH = 240;
    public static final int IMAGE_SPLITTED_HEIGHT = 240;
    public static final int ATTACK_IMAGE_SPLITTED_WIDTH = 640;
}
